### ISSUE TITLE
Error Installing app 

### ISSUE THREAD

**Issue by EnSeal** [DigiThinkIT/repairs#26]
![image](https://user-images.githubusercontent.com/18033246/66137111-81902800-e5f4-11e9-9c4a-9f8355c6fdb9.png)

Hello above is the error when trying to install your app

**Comment by Alchez** [comment]
Hey @EnSeal, we initially wrote this as a generic maintenance-related app, but it's grown to include a lot of custom stuff for our clients, so it's not recommended for use anymore. Sorry about that, but if you want to fork this and remove all those additions, we'll keep this repo public.

For the issue you posted, that is expecting an older version of pip (9.0.3), since it was made for v10. You can either downgrade your pip in the bench's environment, or make a fix to upgrade the app to be used in v11+.
